title: OfficialPixelPower
description: Meine offizielle Streaming‑Seite
theme: jekyll-theme-cayman

# Navigation
navigation:
  - title: Home
    url: /
  - title: Upload‑Plan
    url: /uploadplan/
  - title: Mein Setup
    url: /setup/
  - title: Unterstützen
    url: /support/
  - title: YouTube‑Kanal
    url: /kanal/
