title: OfficialPixelPower
description: Die offizielle PixelPower Seite
theme: jekyll-theme-cayman

# Navigation oben
navigation:
  - title: Home
    url: /
  - title: Upload‑Plan
    url: /uploadplan/
  - title: Mein Setup
    url: /setup/
  - title: News
    url: /news/
  - title: YouTube‑Kanal
    url: /kanal/

# News-Collection
collections:
  news:
    output: true
    permalink: /news/:title/
